### ISSUE TITLE
where is PAJ6100U6 datasheet or sample code?

### ISSUE THREAD

**Issue by nanfang2000** [tinyvision-ai-inc/Vision-FPGA-SoM#2]
where is PAJ6100U6 datasheet or sample code?
how to read the camera data?
Thank you!

**Comment by vr2045** [comment]
Unfortunately, I cannot share the PAJ datasheet which is under NDA.
Sample FPGA code is provided for the Himax sensor that allows obtaining an image. 

Himax is the shipped configuration though the board supports either sensor. The Pixart sensor is not installed on the crowdfunded SoM's.
