### ISSUE TITLE
Schematic - FPGA Pins 35 and 43 Appear To Be Swapped - Please See Attached Image

### ISSUE THREAD

**Issue by whathisface** [tinyvision-ai-inc/Vision-FPGA-SoM#4]
Hello,

The signals:

PX_CLK - Pin 35 of FGPA and
IMAGER_SSN - Pin 43 of the FPGA appear to be swapped in the TINYMODULE-V3 schematic.

Please see the attached:

![swapped](https://user-images.githubusercontent.com/75299769/109375323-b8618080-7870-11eb-88b7-546ca7b7fdd0.jpg)

Regards,
whathisface

**Comment by vr2045** [comment]
Thank you for looking into this! The schematic you're using is from before the crowdfunding. This was updated by moving the pixel clock to pin 43 as shown in the PDC file which is current. 

The reason for the move is that you're not allowed to make pin 35 and input while placing the PLL. By moving the pixel clock to a different pin, the PLL can be placed.

I will update the schematic online so it reflects the latest design...
